name: Deploy Staging
run-name: Deploy to Staging â€¢ ${{ github.ref_name }} by ${{ github.actor }}

on:
  push:
    branches: [main]

env:
  NODE_VERSION: '24.12.0'
  PNPM_VERSION: '10.26.0'
  ENVIRONMENT: staging

jobs:
  Deploy-Web-App:
    runs-on: ubuntu-latest
    steps:
      - name: Install pnpm
        uses: pnpm/action-setup@v4.2.0
        with:
          version: ${{ env.PNPM_VERSION }}
      - name: Setup Node.js
        uses: actions/setup-node@v6.1.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'
      - name: Checkout
        uses: actions/checkout@v6.0.1
        with:
          ref: ${{ github.ref }}
      - name: Install dependencies
        run: pnpm install
        working-directory: apps/web
      - name: Build
        run: pnpm run build
        working-directory: apps/web
      - name: Deploy
        run: pnpm run deploy
        working-directory: apps/web
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_DEPLOY_WEB_STAGING }}
