name: Staging
run-name: Deploy to staging on ${{ github.ref_name }} by ${{ github.actor }}

on:
  push:
    branches: [main]
    paths:
      - 'infra/**'
      - 'apps/**'
      - '.github/workflows/deploy-staging.yml'

concurrency:
  group: deploy-staging
  cancel-in-progress: false

permissions:
  id-token: write # Required for OIDC
  contents: read

env:
  NODE_VERSION: '24.12.0'
  ENVIRONMENT: staging

jobs:
  detect-changes:
    name: Detect Changes
    runs-on: ubuntu-slim
    outputs:
      infra: ${{ steps.filter.outputs.infra }}
      apps: ${{ steps.filter.outputs.apps }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1

      - name: Detect Changed Paths
        uses: dorny/paths-filter@v3.0.2
        id: filter
        with:
          filters: |
            infra:
              - 'infra/**'
            apps:
              - 'apps/**'
              - '.github/workflows/deploy-staging.yml'

  deploy-infra:
    name: Deploy Staging Infra
    needs: detect-changes
    if: needs.detect-changes.outputs.infra == 'true'
    runs-on: ubuntu-slim
    env:
      TF_VAR_root_domain: 'tlds.guide'
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_DEPLOY_INFRA_STAGING }}
      TF_VAR_cloudflare_account_id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      TF_VAR_porkbun_api_key: ${{ secrets.PORKBUN_API_KEY }}
      TF_VAR_porkbun_secret_key: ${{ secrets.PORKBUN_SECRET_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1
        with:
          ref: ${{ github.ref }}

      - name: Configure AWS S3 Remote State
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/github-actions-terraform-staging
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          terraform_version: 1.14.3
          terraform_wrapper: false

      - name: Setup Terragrunt
        uses: gruntwork-io/terragrunt-action@v3.0.2
        with:
          tg_version: 0.96.1
          tf_path: terraform

      - name: Terragrunt Apply
        run: terragrunt run --all apply --non-interactive -- -auto-approve
        working-directory: ${{ github.workspace }}/infra/staging

  deploy-web-app:
    name: Deploy Web App
    needs: [detect-changes, deploy-infra]
    if: |
      always() &&
      needs.detect-changes.outputs.apps == 'true' &&
      (needs.deploy-infra.result == 'success' || needs.deploy-infra.result == 'skipped')
    runs-on: ubuntu-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1
        with:
          ref: ${{ github.ref }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4.2.0

      - name: Setup Node.js
        uses: actions/setup-node@v6.1.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install
        working-directory: apps/web

      - name: Build
        run: pnpm run build
        working-directory: apps/web

      - name: Deploy
        run: pnpm run deploy
        working-directory: apps/web
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_DEPLOY_WEB_STAGING }}
