name: Deploy Staging
run-name: ${{ github.actor }} is testing out GitHub Actions ðŸš€
on: [push]
jobs:
  Deploy-Web-App:
    runs-on: ubuntu-latest
    steps:
      - run: cd ${{ github.workspace }}/apps/web/
      - run: ls -la
