name: Deploy Staging
run-name: Deploy to Staging â€¢ ${{ github.ref_name }} by ${{ github.actor }}

on:
  push:
    branches: [main]

permissions:
  id-token: write # Required for OIDC
  contents: read

env:
  NODE_VERSION: '24.12.0'
  ENVIRONMENT: staging

jobs:
  deploy-infra:
    name: Deploy Infrastructure
    runs-on: ubuntu-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1
        with:
          ref: ${{ github.ref }}

      - name: Configure AWS S3 Remote State
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/github-actions-terraform-staging
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          terraform_version: 1.14.3
          terraform_wrapper: false

      - name: Setup Terragrunt
        uses: gruntwork-io/terragrunt-action@v3.0.2
        with:
          tg_version: 0.96.1
          tf_path: terraform

      - name: Terragrunt Apply (staging, tooling)
        run: |
          terragrunt run --all apply \
            --non-interactive \
            --queue-include-dir "tooling/**" \
            --queue-include-dir "staging/**" \
            --ignore-external-dependencies \
            -- -auto-approve
        working-directory: ${{ github.workspace }}/infra

  depoy-web-app:
    name: Deploy Web App
    needs: deploy-infra
    runs-on: ubuntu-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1
        with:
          ref: ${{ github.ref }}
      - name: Install pnpm
        uses: pnpm/action-setup@v4.2.0
      - name: Setup Node.js
        uses: actions/setup-node@v6.1.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
        working-directory: apps/web
      - name: Build
        run: pnpm run build
        working-directory: apps/web
      - name: Deploy
        run: pnpm run deploy
        working-directory: apps/web
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_DEPLOY_WEB_STAGING }}
