name: Deploy Staging
run-name: ${{ github.actor }} is testing out GitHub Actions ðŸš€
on: [push]

env:
  ENVIRONMENT: staging

jobs:
  Deploy-Web-App:
    runs-on: ubuntu-latest
    steps:
      - name: Install pnpm
        uses: pnpm/action-setup@v4.2.0
        with:
          version: 10.26.2
      - name: Check out repository code
        uses: actions/checkout@v6.0.1
        with:
          ref: ${{ github.ref }}
      - name: Change working directory to apps/web
        run: cd ${{ github.workspace }}/apps/web/
      - name: Build web app
        run: pnpm run build
